[
  {
    id: 1,
    name: "Diamond Ring",
    price: 2500,
    color: "Clear",
    material: "Platinum",
    occasion: "Wedding",
  },
  {
    id: 2,
    name: "Pearl Necklace",
    price: 500,
    color: "White",
    material: "Gold",
    occasion: "Formal",
  },
  {
    id: 3,
    name: "Emerald Earrings",
    price: 1500,
    color: "Green",
    material: "Silver",
    occasion: "Special",
  },
  {
    id: 4,
    name: "Sapphire Bracelet",
    price: 2000,
    color: "Blue",
    material: "Platinum",
    occasion: "Everyday",
  },
  {
    id: 5,
    name: "Ruby Pendant",
    price: 800,
    color: "Red",
    material: "Gold",
    occasion: "Special",
  },
  {
    id: 6,
    name: "Amethyst Earrings",
    price: 400,
    color: "Purple",
    material: "Silver",
    occasion: "Everyday",
  },
  {
    id: 7,
    name: "Topaz Necklace",
    price: 600,
    color: "Yellow",
    material: "Gold",
    occasion: "Formal",
  },
  {
    id: 8,
    name: "Turquoise Ring",
    price: 300,
    color: "Turquoise",
    material: "Silver",
    occasion: "Everyday",
  },
  {
    id: 9,
    name: "Garnet Bracelet",
    price: 500,
    color: "Dark Red",
    material: "Gold",
    occasion: "Special",
  },
  {
    id: 10,
    name: "Aquamarine Earrings",
    price: 700,
    color: "Light Blue",
    material: "Silver",
    occasion: "Formal",
  },
];
